server:
  # O Railway define a porta automaticamente na variável PORT
  port: ${PORT:8080}

spring:
  application:
    name: backend

  datasource:
    # URL Mágica: Monta o endereço usando as variáveis do Railway
    # Se não achar (no seu PC), usa o localhost padrão
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:geothrone_db}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update # Na produção, idealmente seria 'validate', mas 'update' funciona para beta
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuração para evitar erro de CORS (Bloqueio de navegador/celular)
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"