server:
  port: ${PORT:8080}

spring:
  application:
    name: backend

  datasource:
    # URL montada com o host, port e database da sua imagem
    url: ${DATABASE_URL:jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres}

    # Usuário exato mostrado na sua imagem
    username: ${DB_USER:postgres.wunwwivptmwjojiiexpz}

    # Coloque sua senha real aqui
    password: ${DB_PASS:D$T3#9K9HmY/_TC}

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"